Tests to verify google and moyo.ua search
Nikodych/IF-144-TA pull request #3
Opened 2022-05-03 00:15 UTC by Obitotski

2022-05-03 11:28 UTC, Obitotski commented
@Nikodych, thank you for the advice about JS Executer!

2022-05-05 14:36 UTC, Nikodych requested changes

2022-05-05 14:36 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/VerifyMoyoSearchResults.java
> +public class VerifyMoyoSearchResults extends TestRunner {
MoyoSearchTest

2022-05-05 14:36 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/andrewobitotski/GoogleSearchResultsPage.java
> +    public WebElement checkInSearchResult(String mention) {
it's better not to return web elements from the pageobjects

2022-05-06 11:51 UTC, Obitotski commented on src/main/java/com/softserveinc/ita/pageobjects/andrewobitotski/AbstractBasePage.java
> +
done

2022-05-16 13:14 UTC, Nikodych requested changes

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/GoogleSearchTest.java
> +
del new line

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/GoogleSearchTest.java
> +        GoogleSearchPage googleSearchPage = new GoogleSearchPage();
no need variable if it is used once

```
new GoogleSearchPage()
.performSearch(SEARCH_REQUEST)
.checkInSearchResult(MENTION);
```

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/GoogleSearchTest.java
> +        assertTrue(driver
extract into variable, it could be useful during debug

`var currentUrl = driver.getCurrentUrl();`

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/TestRunner.java
> +        BasePage.setDriver(driver);
stat imp of 'setDriver'

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/TestRunner.java
> +        driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(10));
stat import of 'ofSeconds'

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/TestRunner.java
> +        WebDriverManager.chromedriver().setup();
stat import of 'chromedriver()'

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/MoyoSearchTests.java
> +        MoyoHomePage moyo = new MoyoHomePage();
same, if the variable is used only once, better not create variable

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/MoyoSearchTests.java
> +        MoyoHomePage moyo = new MoyoHomePage();
same

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/MoyoSearchTests.java
> +        MoyoHomePage moyo = new MoyoHomePage();
same

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/MoyoSearchTests.java
> +        MoyoHomePage moyo = new MoyoHomePage();
same

2022-05-16 13:14 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/MoyoSearchTests.java
> +        MoyoHomePage moyo = new MoyoHomePage();
same

2022-05-27 12:26 UTC, Nikodych requested changes

2022-05-27 12:26 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/andrewobitotski/GoogleSearchTest.java
> +                .contains(MENTION), "Should be moyo.ua website");
no need to skip to a new line

2022-05-27 15:20 UTC, merged