IFTAQCAB-55 Extract work with table to separate class
Nikodych/IF-144-TA pull request #39
Opened 2022-06-06 14:34 UTC by promahos

2022-06-13 16:17 UTC, promahos commented on src/main/java/com/softserveinc/ita/models/EntityTable.java
> +package com.softserveinc.ita.models;
Agree, I placed it there by mistake.
Moved to pageobjects

2022-06-15 10:51 UTC, Nikodych requested changes

2022-06-15 10:51 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/SubjectsTest.java
> +        newSubjectPage.getTable().goToTablePage("last");
chain

```
newSubjectPage
                .getTable()
                .goToTablePage("last");
```

2022-06-15 10:51 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/SubjectsTest.java
> +        var isAddedAtTheEnd = newSubjectPage.getNamesOfSubjects()
same

2022-06-15 10:51 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/SubjectsTest.java
> +        subjectsPage.getTable().goToTablePage("first");
same

2022-06-15 11:33 UTC, Nikodych approved these changes

2022-06-15 11:33 UTC, merged