IFTAQCAB-31 (Add new group) + IFTAQCAB-33 (Delete group)
Nikodych/IF-144-TA pull request #42
Opened 2022-06-16 10:23 UTC by promahos

2022-06-17 12:07 UTC, Nikodych requested changes

2022-06-17 12:07 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/modals/AddingFormModal.java
> +        if (Objects.requireNonNull(fieldElement
static import of "requireNonNull"

extract into variable "fieldElement.getAttribute("class")"

2022-06-17 12:07 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/modals/AddingFormModal.java
> +
delete extra new line

2022-06-17 12:07 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/steps/GroupsStep.java
> +    public void addNewGroup(GroupEntity group) {
extract into variable 

```
group
                        .getSpeciality()
                        .getName()
```

2022-06-17 12:07 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/steps/GroupsStep.java
> +    public void addNewGroup(GroupEntity group) {
also this

```
group
                        .getFaculty()
                        .getName()
```

2022-06-17 15:50 UTC, promahos commented on src/main/java/com/softserveinc/ita/models/GroupEntity.java
> +    public static String getNewValidName() {
changed similar to SpecialityEntity in order to get already a whole object, not just a string
I'm not sure about moving this to RandomUtil, as it seems to me, that logic, what name is considered to be valid (or not) should be inside the entity class

2022-06-19 16:38 UTC, Nikodych approved these changes

2022-06-19 16:38 UTC, merged