IFTAQCAB-61 Verify functionality to delete test and add Gson lib
Nikodych/IF-144-TA pull request #47
Opened 2022-06-25 16:41 UTC by Obitotski

Added changes (plugin) to pom.xml (about encoding UTF-8 - forgot to add it previously)
Added Gson lib
Added changes to the API method (impl Gson)
Added test for deleting test

2022-06-28 14:17 UTC, Nikodych requested changes

2022-06-28 14:17 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/steps/TestsSteps.java
>      public TestsPage openTestsPage(String subject) {
stop returning anything by methods in step classes, init page variables here, but try to perform all operations in step class if needed, asserts also could be performed here

2022-06-30 12:07 UTC, Obitotski commented
Added test for JSON schema
Added confs to test runner

2022-06-30 13:26 UTC, Nikodych requested changes

2022-06-30 13:26 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/TestsTest.java
> +    public void verifyTestEntitySchemaRecords () {
better to create a separate class for schema verifications, and without using of testrunner

2022-07-01 05:55 UTC, Nikodych requested changes

2022-07-01 05:55 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/ApiJsonSchemaTest.java
> +    public void setUpTestsTests() {
rename

2022-07-01 06:58 UTC, Nikodych approved these changes

2022-07-01 06:58 UTC, merged