IFTAQCAB-32
Nikodych/IF-144-TA pull request #51
Opened 2022-07-02 11:13 UTC by promahos

refactored API methods to avoid boilerplate code
fixed problem with confirm button click while adding
made possible to send API post requests with String instead of Map
added method to create valid FacultyEntity with random field values
added method to get API record for one entity
added custom serializer/deserializer for GroupEntity and method that allows filling connected data from API
changed test logic in order to use UI methods only for test steps, while using API for setting up and tearing down part 
minor changes: spelling mistakes corrected

2022-07-03 13:19 UTC, Nikodych requested changes

2022-07-03 19:44 UTC, promahos commented on src/main/java/com/softserveinc/ita/apisteps/GroupsApiStep.java
> +        //in order to get known given id
changed assert message for a bit

2022-07-04 11:16 UTC, Nikodych requested changes

2022-07-04 11:44 UTC, Nikodych approved these changes

2022-07-04 11:44 UTC, merged